USE music_recommend;

-- 1. Users (password: 123456)
INSERT INTO users (username, password, nickname, email) VALUES
('admin','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','Admin','admin@test.com'),
('user01','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','MusicFan01','u01@test.com'),
('user02','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','MusicFan02','u02@test.com'),
('user03','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','MusicFan03','u03@test.com'),
('user04','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','MusicFan04','u04@test.com'),
('user05','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','MusicFan05','u05@test.com'),
('user06','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','RockFan','u06@test.com'),
('user07','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','FolkLover','u07@test.com'),
('user08','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','HipHopFan','u08@test.com'),
('user09','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','ClassicFan','u09@test.com'),
('user10','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','PopLover','u10@test.com'),
('user11','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','ElectroFan','u11@test.com'),
('user12','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','JazzFan','u12@test.com'),
('user13','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','RnBFan','u13@test.com'),
('user14','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','CampusFolk','u14@test.com'),
('user15','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','MetalHead','u15@test.com'),
('user16','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','IndieFan','u16@test.com'),
('user17','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','CantoneseFan','u17@test.com'),
('user18','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','WesternPop','u18@test.com'),
('user19','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','AncientStyle','u19@test.com'),
('user20','$2b$10$k8/6GsMDR/Ki0iMUvS8mIevLQGymEqfWr9xokm8lUPuOQ1yAl8X9y','TestUser','test@test.com');

-- 2. Artists (50)
INSERT INTO artists (name, description) VALUES
('Jay Chou','King of Mandopop'),
('JJ Lin','Singaporean singer-songwriter'),
('Eason Chan','Hong Kong singer'),
('G.E.M.','Hong Kong singer-songwriter'),
('Joker Xue','Chinese singer-songwriter'),
('Li Ronghao','Chinese singer-songwriter'),
('Hebe Tien','Taiwanese female singer'),
('Mayday','Taiwanese rock band'),
('Coldplay','British rock band'),
('Taylor Swift','American pop star'),
('Ed Sheeran','British singer-songwriter'),
('Adele','British soul singer'),
('Bruno Mars','American pop singer'),
('Beyonce','American pop diva'),
('Justin Bieber','Canadian pop singer'),
('Drake','Canadian rapper'),
('Eminem','American rap legend'),
('Kendrick Lamar','American rapper'),
('Billie Eilish','American new-gen singer'),
('Dua Lipa','British pop singer'),
('Faye Wong','Mandopop diva'),
('Jacky Cheung','God of Songs'),
('Andy Lau','Heavenly King'),
('A-Mei Chang','Taiwanese diva'),
('Jolin Tsai','Asian Dancing Queen'),
('Pu Shu','Chinese folk-rock singer'),
('Xu Wei','Chinese rock singer'),
('Zhao Lei','Chinese folk singer'),
('Mao Buyi','Chinese singer-songwriter'),
('Hua Chenyu','Chinese new-gen singer'),
('Jason Zhang','Chinese power vocalist'),
('Stefanie Sun','Singaporean singer'),
('Fish Leong','Malaysian singer'),
('Karen Mok','Hong Kong singer'),
('David Tao','Godfather of R&B'),
('Khalil Fong','R&B singer-songwriter'),
('Wang Leehom','All-around musician'),
('Will Pan','Hip-hop singer'),
('Luo Dayou','Godfather of music'),
('Li Zongsheng','Music producer'),
('Leslie Cheung','Late superstar'),
('Beyond','Hong Kong legendary band'),
('Sodagreen','Taiwanese indie band'),
('New Pants','Chinese rock band'),
('Omnipotent Youth Society','Indie rock band'),
('Imagine Dragons','American rock band'),
('Maroon 5','American pop-rock band'),
('OneRepublic','American pop-rock band'),
('Linkin Park','American rock band'),
('Queen','British legendary band');
